<h1 style="text-align:center;"><b>Laboratorio 1</b></h1>
<h3 style="text-align:center;">Marcos Díaz (221102), Daniel Machic (22118), Maria Jose Ramírez ()</h3>

**Github**: https://github.com/MajoRC221051/Lab-1---IA

## Librerías

In [ ]:
import numpy as np
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.cluster import KMeans

# **Ejercicio 1**

In [7]:
import numpy as np

def kmeans(X, k, max_iters=100):
    """
    X : matriz de datos (n x d)
    k : número de clusters
    
    Retorna:
    labels : vector de tamaño n con la clase de cada dato
    centroids : matriz k x d con los centroides
    """
    
    n, d = X.shape

    # Inicializar centroides aleatoriamente
    indices = np.random.choice(n, k, replace=False)
    centroids = X[indices]

    for _ in range(max_iters):

        # Paso 1: asignar cada punto al centroide más cercano
        distances = np.zeros((n, k))
        for j in range(k):
            distances[:, j] = np.linalg.norm(X - centroids[j], axis=1)

        labels = np.argmin(distances, axis=1)

        # Paso 2: recalcular centroides
        new_centroids = np.zeros((k, d))
        for j in range(k):
            new_centroids[j] = X[labels == j].mean(axis=0)

        # Verificar convergencia
        if np.allclose(centroids, new_centroids):
            break

        centroids = new_centroids

    return labels, centroids

# Ejemplo de uso
# Crear datos de ejemplo (n x d)
np.random.seed(0)
X = np.random.rand(20, 2)  # 20 puntos en R^2

labels, centroids = kmeans(X, k=3)

print("Vector de labels (n):")
print(labels)

print("\nMatriz de centroides (k x d):")
print(centroids)

Vector de labels (n):
[1 0 0 1 0 0 1 0 2 1 1 1 2 2 0 2 0 2 0 1]

Matriz de centroides (k x d):
[[0.55536705 0.47378412]
 [0.67377826 0.80915417]
 [0.1130383  0.76181579]]


# **Ejercicio 2**

### Inciso A: Dataset Iris

In [10]:
# Cargar datos
iris = load_iris()
X = iris.data

# K-Means desde cero
labels_custom, centroids_custom = kmeans(X, k=3)

# K-Means con scikit-learn
kmeans_sklearn = KMeans(n_clusters=3, random_state=42)
labels_sklearn = kmeans_sklearn.fit_predict(X)

print("Primeros 10 labels (K-Means propio):")
print(labels_custom[:10])

print("\nPrimeros 10 labels (Scikit-learn):")
print(labels_sklearn[:10])

Primeros 10 labels (K-Means propio):
[2 2 2 2 2 2 2 2 2 2]

Primeros 10 labels (Scikit-learn):
[1 1 1 1 1 1 1 1 1 1]


Para el conjunto de datos Iris se utilizó k = 3, de acuerdo con el número de clases presentes en el dataset. Los resultados muestran que tanto el algoritmo de K-Means implementado desde cero como la implementación de Scikit-learn asignan consistentemente las primeras observaciones a un mismo cluster. Las diferencias observadas en los valores numéricos de las etiquetas se deben únicamente a una permutación en la numeración de los clusters, dado que las etiquetas no tienen un significado intrínseco. En términos de estructura del agrupamiento, ambos métodos producen resultados equivalentes.


### Inciso B: Dataset Penguins (Seaborn)

In [15]:
# Cargar dataset
penguins = pd.read_csv("penguins.csv")

# Eliminar filas con valores faltantes
penguins = penguins.dropna()

# Seleccionar solo variables numéricas
X = penguins[['bill_length_mm',
              'bill_depth_mm',
              'flipper_length_mm',
              'body_mass_g']].values

# K-Means desde cero
labels_custom, centroids_custom = kmeans(X, k=3)

print("K-Means propio")
print("Labels (primeros 10):")
print(labels_custom[:10])

print("\nCentroides:")
print(centroids_custom)

# K-Means con scikit-learn
kmeans_sklearn = KMeans(n_clusters=3, random_state=42)
labels_sklearn = kmeans_sklearn.fit_predict(X)

print("\nK-Means Scikit-learn")
print("Labels (primeros 10):")
print(labels_sklearn[:10])

print("\nCentroides:")
print(kmeans_sklearn.cluster_centers_)

K-Means propio
Labels (primeros 10):
[1 1 1 1 1 1 0 1 1 0]

Centroides:
[[  44.24336283   17.44778761  201.54867257 4310.61946903]
 [  41.12214286   17.94642857  189.62857143 3461.25      ]
 [  48.6625       15.3975      219.9875     5365.9375    ]]

K-Means Scikit-learn
Labels (primeros 10):
[0 0 0 0 0 0 2 0 0 2]

Centroides:
[[  41.12214286   17.94642857  189.62857143 3461.25      ]
 [  48.6625       15.3975      219.9875     5365.9375    ]
 [  44.24336283   17.44778761  201.54867257 4310.61946903]]


Para el conjunto de datos Penguins se realizó un agrupamiento utilizando k = 3, consistente con el número de especies presentes en el dataset. El algoritmo de K-Means implementado desde cero y la implementación de Scikit-learn producen agrupamientos equivalentes. Si bien los vectores de etiquetas asignadas a cada observación difieren numéricamente, los centroides obtenidos son los mismos, salvo por una permutación en el orden de los clusters. Estas diferencias se deben a la inicialización aleatoria de los centroides y al hecho de que los identificadores de los clusters no tienen un significado intrínseco. En términos de estructura del agrupamiento, ambos métodos generan resultados equivalentes.

### Inciso C: Dataset Wine Quality (winequality-red)

In [18]:
# Cargar datos (ajusta la ruta si es necesario)
wine = pd.read_csv("winequality-red.csv", sep=";")

X = wine.drop(columns=['quality']).values

# K-Means desde cero
labels_custom, _ = kmeans(X, k=3)

# K-Means con scikit-learn
kmeans_sklearn = KMeans(n_clusters=3, random_state=42)
labels_sklearn = kmeans_sklearn.fit_predict(X)

print("Primeros 10 labels (K-Means propio):")
print(labels_custom[:10])

print("\nPrimeros 10 labels (Scikit-learn):")
print(labels_sklearn[:10])

Primeros 10 labels (K-Means propio):
[0 2 2 2 0 2 2 0 0 1]

Primeros 10 labels (Scikit-learn):
[0 1 1 1 0 0 1 0 0 2]


En el conjunto de datos Wine Quality, los resultados obtenidos mediante el algoritmo de K-Means implementado desde cero y la versión de Scikit-learn muestran diferencias en las etiquetas asignadas a las observaciones. A diferencia de otros conjuntos de datos analizados, este dataset no presenta una estructura de clusters claramente definida, lo que hace que el algoritmo sea sensible a la inicialización de los centroides. En consecuencia, distintas ejecuciones del algoritmo pueden conducir a particiones diferentes pero igualmente válidas desde el punto de vista de la función objetivo de K-Means. Esto evidencia una mayor inestabilidad del método en conjuntos de datos con alto solapamiento entre observaciones.

# **Ejercicio 3**

# **Ejercicio 4**

# **Ejercicio 5**

# **Ejercicio 6**